creation_rules:
  - path_regex: \.sops\.yaml$
    key_groups:
      - age:
          # ken (one@K01dra)
          - age145wjxs054fzlet5lnr7jtktke4dg26xx9ccnayy886l2jfk4v9eqf4velt

  - path_regex: \.tfvars$
    key_groups:
      - age:
          - age145wjxs054fzlet5lnr7jtktke4dg26xx9ccnayy886l2jfk4v9eqf4velt
