apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ayo-portal.fullname" . }}-worker
  labels:
    {{- include "ayo-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ayo-portal.name" . }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ayo-portal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: {{ include "ayo-portal.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bench", "worker", "--queue", "short,default,long"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: {{ include "ayo-portal.fullname" . }}-sites
