apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ayo-portal.fullname" . }}-secrets
  labels:
    {{- include "ayo-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_ROOT_PASSWORD: {{ .Values.postgresql.rootPassword | quote }}
  ADMIN_PASSWORD: {{ .Values.adminPassword | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
