apiVersion: v1
kind: Service
metadata:
  name: {{ include "ayo-portal.fullname" . }}-backend
  labels:
    {{- include "ayo-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: {{ include "ayo-portal.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - port: 8000
      targetPort: http
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ayo-portal.fullname" . }}-frontend
  labels:
    {{- include "ayo-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: {{ include "ayo-portal.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - port: 8080
      targetPort: http
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ayo-portal.fullname" . }}-websocket
  labels:
    {{- include "ayo-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  selector:
    app.kubernetes.io/name: {{ include "ayo-portal.name" . }}
    app.kubernetes.io/component: websocket
  ports:
    - port: 9000
      targetPort: ws
      name: ws
